{% set name = "jsonrpcclient" %}
{% set version = "4.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c0d475494b3e1b591ecdee7883739accaf5695edb673f16b7383b8c6bbdb1ca3

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - jsonrpc=jsonrpcclient.__main__:main
  noarch: python

requirements:
  host:
    - pip
    - setuptools
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - jsonrpcclient

about:
  home: https://github.com/bcb/jsonrpcclient
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Send JSON-RPC requests in Python.
  doc_url: https://jsonrpcclient.readthedocs.io/
  dev_url: https://github.com/bcb/jsonrpcclient

extra:
  recipe-maintainers:
    - bcb
    - beenje
