{% set name = "jsonrpcclient" %}
{% set version = "3.3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2f2d218de00ff7532f69efed2e2515d30c90f873e5cb91bf00de996dfb782f8a

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - jsonrpc=jsonrpcclient.__main__:main
  noarch: python

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - python >=3.5
    - apply_defaults <1
    - click <7
    - jsonschema <4

test:
  imports:
    - jsonrpcclient

about:
  home: https://github.com/bcb/jsonrpcclient
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Send JSON-RPC requests in Python.
  doc_url: https://jsonrpcclient.readthedocs.io/
  dev_url: https://github.com/bcb/jsonrpcclient

extra:
  recipe-maintainers:
    - bcb
