travis:
  secure:
    BINSTAR_TOKEN: pPJB0k9u4zUf1LN2Ms+tudgqUuIex4svTKXZj4Swv4RaJTVGf1NwyFj4+qkCTN6nXzYq+/ze1Tc9wWYiQzn8X3pGWmmp46I2aqK8dYwal/Af0BpQRVOJbKCrjfdPc8jy4XrtMWLaB8lFWfwfX2kJK15NAWMHslNHmfqCJRQA/eTojd8a0kw7EKctWIwi1BhCSATiaPo0pLaV1C/Pedeo43c2A2/d5+f7nPpcqegF3vk7lI3ISCsxDAVEMRGerEjej/ZGr9jVp+2XaWn93XOe8bWVbNQplvC2BpUFw1tRt1YtTzzX22hNy9DRfOhvFF8qqzHWezyztMJJhGWlUWVlq1SGFz0rXsOqBYdO6EWMgv9DFmRcCP+3kneFY27uhoVH9jQuVqvT1HQfoqWOcZrqaoU4vuo/oaFnrfd1fIlwc6t1KEIp1F0LefOSHypONss8kSeFmJc9kkphh7dV67EUbQZN9Lx+VVSiPohnDBLndpw0WpIu55QxbmotnSk4eYfjLj19rYytppJZAshnOp/oUsTIyqEDFN86tJK/tW2qVxuxLp1YcXJ1ZZkWMsGtPfDvdl1RJ3Cj0Rt1ObqLZRwdah9Q3GQpb8CYSsWV6GRSkjFxHIHja4PH5jCJy3mDEIc33Xm+El4nxBt4YXwU/grwr2Hi8UIdkfVtz/W1g4A4fcg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
