travis:
  secure:
    BINSTAR_TOKEN: fY6Aa6qONdKYqsHraFUYnUyoaTWCq/ivasQWOEQX2xm0i9kbuwoq291cb6U67Gj02XbU9suyNnHeqe8D7XXax/1Ed0Da7OXHRffYZsw9GcPJ0Od/mqf6oVrHRdB1pzYjohv8RlL5ExDFbZX1d7h7LismcAZMrTNxt/FeTQ6umeyfL43OeXygOO4HzlyIo4rGEk3zrCKxpr+OiwLX4InzBcFGUspm+d+a0VlQHWTetkxrfo62ZzAVSTA7hlVZN0iRld7v7GjqYAuZa9cy9T2DFN0Z3PM286u5hXX2YvP7udBaER2ZuUMEo+V0/RtAQfW2K3urLDC9Gj5AHGYoPfsXtjART5YoIeHJGc1dLuXB6ZytTHEffG6c0A95Z61GbnOwRRsyEXgZU/xQUN9slqcfYcG1iFGrbBr524LnjG6uH4E54diovSNLev6tqS14JKuC0+y3o0MSZHqa9LaygZcg/+CZ/U0JcKvq0bj1Bl5djTIUQCGZmgFmqQm14gMOPixpUwO+NQOVZ9YlNba2o2yp8pYnQuOuYtImKxrtj4dkezxbpijrzT+etAyFTHWdHku0iDaY+plbbrZ35svs/XUNHqkIOeCrzzGcvSpxvxxvG03g0PPIJgzD5AUG+05Sx5x32bumAsBgSZTnpCWNwnlFf8OWVw8x2EJGNSbrnkXp65w=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
