travis:
  secure:
    BINSTAR_TOKEN: YenSHjE15jlM1+1qCKRPCdBYSEACJxt6dWImXkR1r2ZqJ5BpDOLzJ+FONv02qB8M97rXDc3jwizy8C/ZNVGBaWdSyeEV7GRwH+PhcXTs1FeIuWA0feZ+7FG7gYVVYt6xanwCmfUPy97pMPPO53itet/oBduR29DffI6vc1lQe2msSGOSxt6cJf8EDjYgLBQzvLewCsJ9Wrt/kGRcmchR3WRfNIZtZJyazzEnFYW4Qu28jd/BqaJBdbnj2JfVvTAVUGnKIUAckOhmH2fr0pd8CPkVS2yM/ujL9KECAZwkKLhwHxPh/h8y58dSxInAK1Li4v3Kd6Q/ALtXW19YspzJ0oc+UBO3E1KLD3PfmqrEP2aJdNoZLqPEirE3psWXbnG2pOg0yvp4ZhebV4+4obGJKjKctpxHZP8Q1Hi8ox4DeOUpuV5PmiA7D3ZJS0KFGkxlwDDX/tyigw2CUDj/uvgz//nIeoGErkMAXQpqfyAlIVHVn0zSUoVsKXPS1z/pc6MyKpJlpLuu3DsfKMJw+NCEpqTOI1hQlMqlFsNGQJJO+kEa6V/9dqHv+i3qd6+owDi6nZvkUpUFOGMI9a4nCaJewzdpmrjz5QTvARypHoS1mdHqf1rahXr2g1Ur+dSTrWoG/+QhBO0E2Txam8OnxoWds0F5IDc9dlv7fmGc60zFE7M=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
